OnLine/OnLine/Models/ErrorViewModel.cs
using System;

namespace OnLine.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OnLine/OnLine/Controllers/ExaminerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace OnLine.Controllers
{
    public class ExaminerController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

OnLine/OnLine/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OnLine.Models;

namespace OnLine.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OnLine/OnLine/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Online.Infrastructure.MyCourse;
using Online.DomainModel;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace OnLine.Controllers
{
    public class StudentController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
                var studentService = new StudentService();
           
                var students = studentService.GetAll();
                ViewData["Students"] = students;
          
               
                return View();
        }

        public IActionResult Detail(Student student)
        {
            var userService = new StudentService();
            var model = userService.GetUserById(student.Sid);
            return View(model);
        }

        public IActionResult StudentDel(int sid)
        {

            var userService = new StudentService();
            userService.StudentDel(sid) ;
           
            return Redirect(Url.Action("Index", "Student"));
        }

        public IActionResult AddUser(Student student)
        {
            var userService = new StudentService();
            var count = userService.StudentAdd(student.Sid,student.Sname,student.Depart,student.Class,student.Major,student.Password);
            return Redirect(Url.Action("Index", "Student"));
        }
        public IActionResult UpdateUser(Student student)
        {
            var userService = new StudentService();
            var ab = userService.UpdateUser(student.Sid,student.Sname,student.Depart,student.Class,student.Major,student.Password);
            return Redirect(Url.Action("Index", "Student"));
        }


    }
}

OnLine/OnLine/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace OnLine.Controllers
{
    public class TeacherController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

OnLine/OnLine/Views/Home/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>在线考试系统-登录</title>

    <!-- Bootstrap CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="css/bootstrap-theme.css" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href="css/elegant-icons-style.css" rel="stylesheet" />
    <link href="css/font-awesome.css" rel="stylesheet" />
    <!-- Custom styles -->
    <link href="css/style.css" rel="stylesheet">
    <link href="css/style-responsive.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
      <![endif]-->
    <!-- =======================================================
      Theme Name: 权限管理系统
      Theme URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
      Author: BootstrapMade
      Author URL: https://bootstrapmade.com
    ======================================================= -->
</head>

<body class="login-img3-body">

    <div class="container">

        <form class="login-form">
            <div class="login-wrap">
                <p class="login-img"><i class="icon_lock_alt"></i></p>
                <div class="input-group">
                    <span class="input-group-addon"><i class="icon_profile"></i></span>
                    <input type="text" class="form-control" placeholder="学号" autofocus>
                </div>
                <div class="input-group">
                    <span class="input-group-addon"><i class="icon_key_alt"></i></span>
                    <input type="password" class="form-control" placeholder="密码">
                </div>                                  
                <label class="col-10">
                    选择角色
                    <select class="m-bot10">
                        <option>请选择</option>
                        <option>管理员</option>
                        <option>学生</option>
                        <option>教师</option>
                        <option>审题员</option>
                    </select>

                </label>
                
                @*<label class="checkboxes">

                        <!--
           <span class="pull-right"> <a href="#"> 忘记密码?</a></span>
           <input type="checkbox" value="remember-me">记住密码
        -->
                        <!--
           <span class="pull-right"> <a href="#"> 忘记密码?</a></span>
           <input type="checkbox" value="remember-me">记住密码
        -->
                        <input type="checkbox" />学生

                        <input type="checkbox" />教师
                        <input type="checkbox" />管理员
                        <input type="checkbox" />审题员
                        <!--
           <span class="pull-right"> <a href="#"> 忘记密码?</a></span>
           <input type="checkbox" value="remember-me">记住密码
        -->

                    </label>*@
                <a class="btn btn-primary btn-lg btn-block" type="submit" href='@Url.Action("Privacy","Home")'>登录</a>
                <a  class="btn btn-info btn-lg btn-block" type="submit" href='@Url.Action("AddUser","Student")'>注册</a>
            </div>
        </form>
    </div>
    <script>

    </script>

</body>

</html>

OnLine/OnLine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="~/img/favicon.png">

    <title>在线考试系统</title>

    <!-- Bootstrap CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="~/css/bootstrap-theme.css" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href="~/css/elegant-icons-style.css" rel="stylesheet" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <!-- full calendar css-->
    <link href="~/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css" rel="stylesheet" />
    <link href="~/assets/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" />
    <!-- easy pie chart-->
    <link href="~/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen" />
    <!-- owl carousel -->
    <link rel="stylesheet" href="~/css/owl.carousel.css" type="text/css">
    <link href="~/css/jquery-jvectormap-1.2.2.css" rel="stylesheet">
    <!-- Custom styles -->
    <link rel="stylesheet" href="~/css/fullcalendar.css">
    <link href="~/css/widgets.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/style-responsive.css" rel="stylesheet" />
    <link href="~/css/xcharts.min.css" rel=" stylesheet">
    <link href="~/css/jquery-ui-1.10.4.min.css" rel="stylesheet">
    <!-- =======================================================
      Theme Name: 权限管理系统
      Theme URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
      Author: BootstrapMade
      Author URL: https://bootstrapmade.com
    ======================================================= -->
</head>
<body>
    <!-- container section start -->
    <section id="container" class="">

        <!-- 标题栏 -->
        <header class="header dark-bg">
            <div class="toggle-nav">
                <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
            </div>

            <!--logo start-->
            <a href='@Url.Action("Privacy","Home")' class="logo">在线考试系统</a>
            <!--logo end-->
            <!--  search form start 搜索框-->
            <div class="nav search-row" id="top_menu">
                <!--  search form start 搜索框-->
                <ul class="nav top-menu">
                    <li>
                        <form class="navbar-form">
                            <input class="form-control" placeholder="Search" type="text">
                        </form>
                    </li>
                </ul>
                <!--  search form end -->
            </div>
            

            <div class="top-nav notification-row">
                <!-- notificatoin dropdown start-->
                <ul class="nav pull-right top-menu">

                    <!-- task notificatoin start 通知栏 -->
                    
                    <!-- task notificatoin end -->
                    <!-- inbox notificatoin start-->
                    
                    <!-- inbox notificatoin end -->
                    <!-- alert notification start-->
                   
                    <!-- alert notification end-->
                    <!-- user login dropdown start 通知栏-->
                    
                    <li>
                       <i class="fa "></i> <a href='@Url.Action("Index","Home")'>退出</a>
                    </li>
                       
                       
                   
                    <!-- user login dropdown end -->
                </ul>
                <!-- notificatoin dropdown end-->
            </div>
        </header>
        <!--header end-->
        <!--sidebar start 侧边栏-->
        <aside>
            <div id="sidebar" class="nav-collapse ">

                <ul class="sidebar-menu">
                    <li class="active">
                        <a class="" href='@Url.Action("Privacy","Home")'>
                            <i class="icon_house_alt"></i>
                            <span>首页</span>
                        </a>
                    </li>

                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="fa fa-user"></i>
                            <span>用户管理</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            <li><a class="" href='@Url.Action("Index","Student")'>学生基本信息管理</a></li>
                            <li><a class="" href='@Url.Action("Index","Teacher")'>老师基本信息管理</a></li>
                            <li><a class="" href='@Url.Action("Index","Examiner")'>审题员基本信息管理</a></li>
                            @*<li><a class="" href='@Url.Action("Login","User")'>用户登录管理</a></li>*@
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="fa fa-group"></i>
                            <span>在线考试</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            <li><a class="" href='@Url.Action("Index","Role")'>模拟考试</a></li>
                            <li><a class="" href='@Url.Action("Detail","Role")'>正式考试</a></li>
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="fa fa-sitemap "></i>
                            <span>成绩查询</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            <li><a class="" href='@Url.Action("Index","Group")'>老师查询成绩</a></li>
                            <li><a class="" href='@Url.Action("Detail","Group")'>学生查询成绩</a></li>
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="fa fa-key"></i>
                            <span>个人信息管理</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            <li><a class="" href='@Url.Action("Index","Access")'>个人信息管理</a></li>
                            <li><a class="" href='@Url.Action("Detail","Access")'>access</a></li>
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="fa fa-key"></i>
                            <span>试题管理</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            <li><a class="" href='@Url.Action("Index","Access")'>试题管理</a></li>
                            <li><a class="" href='@Url.Action("Detail","Access")'>access</a></li>
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="fa fa-key"></i>
                            <span>题库管理</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            <li><a class="" href='@Url.Action("Index","Access")'>题库导出</a></li>
                            <li><a class="" href='@Url.Action("Detail","Access")'>题库导入</a></li>
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="fa fa-key"></i>
                            <span>试卷导出</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            <li><a class="" href='@Url.Action("Index","Access")'>试卷导出</a></li>
                            <li><a class="" href='@Url.Action("Detail","Access")'>access</a></li>
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="fa fa-key"></i>
                            <span>出题</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            <li><a class="" href='@Url.Action("Index","Access")'>出题</a></li>
                            <li><a class="" href='@Url.Action("Detail","Access")'>access</a></li>
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="fa fa-key"></i>
                            <span>试题审核</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            <li><a class="" href='@Url.Action("Index","Access")'>试题审核</a></li>
                            <li><a class="" href='@Url.Action("Detail","Access")'>access</a></li>
                        </ul>
                    </li>
                    

                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            @RenderBody()
        </section>
        <!--main content end-->
    </section>

    <!-- container section start -->
    <!-- javascripts -->
    <script src="~/js/jquery.js"></script>
    <script src="~/js/jquery-ui-1.10.4.min.js"></script>
    <script src="~/js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="~/js/jquery-ui-1.9.2.custom.min.js"></script>
    <!-- bootstrap -->
    <script src="~/js/bootstrap.min.js"></script>
    <!-- nice scroll -->
    <script src="~/js/jquery.scrollTo.min.js"></script>
    <script src="~/js/jquery.nicescroll.js" type="text/javascript"></script>
    <!-- charts scripts -->
    <script src="~/assets/jquery-knob/js/jquery.knob.js"></script>
    <script src="~/js/jquery.sparkline.js" type="text/javascript"></script>
    <script src="~/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
    <script src="~/js/owl.carousel.js"></script>
    <!-- jQuery full calendar -->
    <script src="~/js/fullcalendar.min.js"></script>
    <!-- Full Google Calendar - Calendar -->
    <script src="~/assets/fullcalendar/fullcalendar/fullcalendar.js"></script>
    <!--script for this page only-->
    <script src="~/js/calendar-custom.js"></script>
    <script src="~/js/jquery.rateit.min.js"></script>
    <!-- custom select -->
    <script src="~/js/jquery.customSelect.min.js"></script>
    <script src="~/assets/chart-master/Chart.js"></script>

    <!--custome script for all page-->
    <script src="~/js/scripts.js"></script>
    <!-- custom script for this page-->
    <script src="~/js/sparkline-chart.js"></script>
    <script src="~/js/easy-pie-chart.js"></script>
    <script src="~/js/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/js/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/js/xcharts.min.js"></script>
    <script src="~/js/jquery.autosize.min.js"></script>
    <script src="~/js/jquery.placeholder.min.js"></script>
    <script src="~/js/gdp-data.js"></script>
    <script src="~/js/morris.min.js"></script>
    <script src="~/js/sparklines.js"></script>
    <script src="~/js/charts.js"></script>
    <script src="~/js/jquery.slimscroll.min.js"></script>
    <script>
        //knob
        $(function () {
            $(".knob").knob({
                'draw': function () {
                    $(this.i).val(this.cv + '%')
                }
            })
        });

        //carousel
        $(document).ready(function () {
            $("#owl-slider").owlCarousel({
                navigation: true,
                slideSpeed: 300,
                paginationSpeed: 400,
                singleItem: true

            });
        });

        //custom select box

        $(function () {
            $('select.styled').customSelect();
        });

        /* ---------- Map ---------- */
        $(function () {
            $('#map').vectorMap({
                map: 'world_mill_en',
                series: {
                    regions: [{
                        values: gdpData,
                        scale: ['#000', '#000'],
                        normalizeFunction: 'polynomial'
                    }]
                },
                backgroundColor: '#eef3f7',
                onLabelShow: function (e, el, code) {
                    el.html(el.html() + ' (GDP - ' + gdpData[code] + ')');
                }
            });
        });
    </script>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</body>
</html>

OnLine/OnLine/Views/Student/Apoint.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<section class="wrapper">
    <div class="text-center">
        <h1 class="display-4">分配权限点</h1>
    </div>
    <div class="col-lg-10">
        <section class="panel">
            <div class="panel-body">
                <form class="form-horizontal " method="get">
                    <div class="form-group">
                        <label class="control-label col-lg-2" for="inputSuccess">您已选择的用户：</label>
                        <div class="box-content">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>用户ID</th>
                                        <th>用户名称</th>
                                        <th>所属用户组</th>
                                        <th>角色</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td>1001</td>
                                        <td>jack</td>
                                        <td>设计部</td>
                                        <td>总监</td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td>1002</td>
                                        <td>Linda</td>
                                        <td>人事部</td>
                                        <td>职员</td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td>1003</td>
                                        <td>Spadn</td>
                                        <td>研发部</td>
                                        <td>职员</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-lg-2" for="inputSuccess">选择权限点</label>
                            <div class="col-lg-10">
                                <select class="form-control m-bot15">
                                    <option>增加用户</option>
                                    <option>删除用户</option>
                                    <option>增加角色</option>
                                    <option>删除用户组</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-offset-5 col-lg-10">
                            <button type="submit" class="btn btn-danger">确定</button>
                            <button type="submit" class="btn btn-danger">取消</button>
                        </div>
                     </div>
                   </form>
            </div>
        </section>
    </div>
</section>

OnLine/OnLine/Views/Student/Detail.cshtml
@using Online.Infrastructure.MyCourse;
@model Student
@{
    var student = Model;
}
<!DOCTYPE html>
<html>

<head>
    <title>用户添加</title>
</head>

<body class="login-img3-body">
    <section class="wrapper">
        <div class="text-center">
            <h1 class="display-4">用户明细信息页面</h1>
        </div>
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    用户信息
                </header>
                <div class="panel-body">
                    <div class="form">
                        <form id="formSearch" class="form-validate form-horizontal" method="get" action="@Url.Action("UpdateUser","Student")" novalidate="novalidate">
                            <div class="form-group ">
                                <label for="uid" class="control-label col-lg-2">用户Id <span class="required">*</span></label>
                                <div class="col-lg-10">
                                    <input class="form-control" value="@student.Sid" minlength="5" type="text" required="" disabled />
                                    <input id="sid" value="@student.Sid" name="sid" type="hidden" />
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="uname" class="control-label col-lg-2">用户名称 <span class="required">*</span></label>
                                <div class="col-lg-10">
                                    <input class="form-control" id="sname" value="@student.Sname" name="sname" minlength="5" type="text" required="">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="uname" class="control-label col-lg-2">学院 <span class="required">*</span></label>
                                <div class="col-lg-10">
                                    <input class="form-control" id="depart" value="@student.Depart" name="depart" minlength="5" type="text" required="">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="uname" class="control-label col-lg-2">班级 <span class="required">*</span></label>
                                <div class="col-lg-10">
                                    <input class="form-control" id="Class" value="@student.Class" name="Class" minlength="5" type="text" required="">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="uname" class="control-label col-lg-2">专业 <span class="required">*</span></label>
                                <div class="col-lg-10">
                                    <input class="form-control" id="major" value="@student.Major" name="major" minlength="5" type="text" required="">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="uname" class="control-label col-lg-2">密码 <span class="required">*</span></label>
                                <div class="col-lg-10">
                                    <input class="form-control" id="password" value="@student.Password" name="password" minlength="5" type="text" required="">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-primary" type="submit" onclick="change()">Save</button>
                                    <button class="btn btn-default" type="button">Cancel</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </section>
        </div>
    </section>
    <script type="text/javascript">
        @*function change(uid) {
            var url =@Url.Action("Detail", "User")+'?uid=' + uid;
            location.href = url;
        }*@
        function change() {
            var form = document.getElementById("formSearch");
            form.submit();
        }
    </script>
</body>
</html>